//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorTabla
    {
        public int TablaId { get; set; }
        public int ItemId { get; set; }
        public string Denominacion { get; set; }
        public string DesCorta { get; set; }
        public string Valor { get; set; }
    }
}
